# Generated by Django 3.2 on 2021-04-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casualmarking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marker',
            options={'verbose_name': 'marker', 'verbose_name_plural': 'markers'},
        ),
    ]
