# Generated by Django 3.2 on 2021-04-28 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casualmarking_app', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casualmarking_app.marker')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casualmarking_app.student')),
            ],
        ),
    ]
