# Generated by Django 3.2 on 2021-04-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casualmarking_app', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(null=True, upload_to='attachments'),
        ),
    ]
