# Generated by Django 3.2 on 2021-04-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casualmarking_app', '0005_task_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
    ]
