# Generated by Django 3.2 on 2021-04-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casualmarking_app', '0007_auto_20210428_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
